### ISSUE TITLE
When changing Rate 'Types' the values should reset to their defaults

### ISSUE THREAD

**Issue by 32bitsofgil** [YoyoMario/TiltBetaBuilds#10]
Currently if I change from the default "BetaFlight" rates calculator to the "Raceflight" rates, the default Betaflight values stay populated and result in very slow rate curves that are unflyable. When selecting the new rate calculator the rates should default to whatever is the default for those selected. For example Raceflight rates should default to 400, 50, 150 when changing the drop down menu, and should change back to whatever defaults are for Betaflight when selected.

**Comment by YoyoMario** [comment]
@32bitsofgil fixed.
