### ISSUE TITLE
Drone slowly falls back down when tilted up for launch mode

### ISSUE THREAD

**Issue by 32bitsofgil** [YoyoMario/TiltBetaBuilds#13]
Seems almost like the motors are spinning to slow to maintain angle and the drone slowly falls back down flat.

**Comment by 32bitsofgil** [comment]
It is possible this issue is related to the removal of deadband. I think my controller needs a slight amount of deadband for it to properly fly without input.

**Comment by YoyoMario** [comment]
@32bitsofgil i think its your controller, we'll add deadband soon
