### ISSUE TITLE
Betaflight and KISS rates not being calculated/unexpected results.

### ISSUE THREAD

**Issue by sethrobin** [YoyoMario/TiltBetaBuilds#25]
Basically, I can't get Betaflight or KISS rates to work on this version. Confirmed working in the previous build. I used an old profile, made a new one, started from flight one, etc and nothing worked. Please see the video for a demonstration. 

First half of the video is for another, more minor issue.

http://cloud.sethrobinson.net/fc309eb22b2c

**Comment by YoyoMario** [comment]
@sethrobin oh wow, thanks for the video!
I'll check it out tomorrow after work (pretty late here now).

**Comment by YoyoMario** [comment]
@sethrobin Hey, fixed the issue! 👍
