### ISSUE TITLE
Using a slash "/" in a profile name throws a path error.

### ISSUE THREAD

**Issue by sethrobin** [YoyoMario/TiltBetaBuilds#27]
Using a slash "/" in a profile name throws a path error.
<img width="1680" alt="Screen Shot 2019-05-17 at 9 07 54 PM" src="https://user-images.githubusercontent.com/1739877/57963313-0c8fb080-78e8-11e9-8d94-c8048ffac714.png">

**Comment by YoyoMario** [comment]
@sethrobin solved! Thanks as per usual :)
