### ISSUE TITLE
Betaflight rates do not seem to compute properly.

### ISSUE THREAD

**Issue by sethrobin** [YoyoMario/TiltBetaBuilds#5]
I used Apoc's rate calculator to convert my BF rates to RF and my RaceFlight rates plugged into Tilt just fine. However, entering my Betaflight rates directly yielded unexpected results, so I expect there's a math issue. Shown below are the Betaflight and Raceflight values that come close to matching my rates. I arrived at the BF rates through trial and error.

<img width="1680" alt="Screen Shot 2019-04-15 at 4 38 19 PM" src="https://user-images.githubusercontent.com/1739877/56167434-c3250c00-5f9d-11e9-962d-62e3e241971d.png">
<img width="1680" alt="Screen Shot 2019-04-15 at 4 38 11 PM" src="https://user-images.githubusercontent.com/1739877/56167435-c3250c00-5f9d-11e9-98ad-892ba1accada.png">

**Comment by sethrobin** [comment]
Here are my standard rates.
<img width="1680" alt="Screen Shot 2018-11-17 at 10 40 33 PM" src="https://user-images.githubusercontent.com/1739877/56167519-067f7a80-5f9e-11e9-953a-f236f7e88c7a.png">

**Comment by YoyoMario** [comment]
@sethrobin Hey! Thannks for submitting this issue! We are avare, since default setting on the beginning was Race1, once we introduced KISS and BF their expo and super rates are switched up. You should try just swithing those values... I'll give it a try as of this moment right now

**Comment by YoyoMario** [comment]
@YoyoMario Hey, just tried those values, something is off... is that velocidrone? It says "inspired by betaflight" are we even sure they are using the real calculations? I tried matching values with Air2, and ours are same as on Air2... I have to try DRL Sim yet to see if theirs is the same as ours

**Comment by YoyoMario** [comment]
@sethrobin And something is definetly wrong with BF rates
