### ISSUE TITLE
Dashboard hangs when selecting Betaflight as the rate type.

### ISSUE THREAD

**Issue by sethrobin** [YoyoMario/TiltBetaBuilds#6]
Dashboard hangs when selecting Betaflight as the rate type. 

Video: http://cloud.sethrobinson.net/3e784f6a11f1

I have seen this when accidentally entering whole numbers while in BF mode as well. After entering an initial value, if I want to change it, I have to explicitly enter the 1's digit. Such as: "0.62" instead of ".62" because it will ignore the "." without the leading zero and take "62" as the entry, which sometimes locks up the modal window.

<img width="698" alt="Screen Shot 2019-04-16 at 2 34 30 PM" src="https://user-images.githubusercontent.com/1739877/56238738-c62f0380-6054-11e9-8001-a6f40cbce76d.png">

[Player.log](https://github.com/YoyoMario/TiltBetaBuilds/files/3086602/Player.log)

**Comment by sethrobin** [comment]
Video link not working. Stand by.

**Comment by YoyoMario** [comment]
Yup, just wanted to DM you about that

**Comment by sethrobin** [comment]
Link updated http://cloud.sethrobinson.net/3e784f6a11f1
